### ISSUE TITLE
kemono.su is broken!

### ISSUE THREAD

**Issue by NotVoid404** [keiyoushi/tachiyomi-extensions-source#5883]
### Source information

kemono 1.4.14

### Source language

multi

### Steps to reproduce

click on any chapter

also try opening webview

### Expected behavior

gives the chapter of what i clicked one

### Actual behavior

clicking on any chapter gives me 
open failed: ENOENT ( no such file or directory)
or something else that too long
also, webView doesn't work 

### Mihon/Tachiyomi version

0.17.0

### Android version

im not sure

### Other details

i suck at this but i think you understand me. right?

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by NotVoid404** [comment]
The site itself is working.

**Comment by Smol-Ame** [comment]
ENOENT is a personal issue of putting your app's folder in an unreachable spot. Go check with app support for help/more details.

As for the actual error/issue:
![Screenshot_20241104_151420_Mihon.png](https://github.com/user-attachments/assets/b2d20ae8-6e55-4d98-ab5e-bbb99da11872)

**Comment by OMAR-SH69** [comment]
any fix?

**Comment by Smol-Ame** [comment]
@OMAR-SH69 you can see that the issue is still open & there's no fix linked to the issue. Commenting unnecessarily sends an email to everyone involved in the issue & pings the server channel.

There's over 400~ issues in the repo with less than a handful of contributors contributing their time & willingness to fix things. Wait patiently for a fix, migrate to a different source, contribute yourself, or find something else to use.

**Comment by OMAR-SH69** [comment]
@Smol-Ame sorry my bad. it's my first time commenting on github so i don't understand it that much

**Comment by towermom9** [comment]
@choppeh @KenjieDec @stevenyomi maybe you guys could help? (Sorry for the mentions, saw some commits that were made to the kemono extension by you guys)

~~After an hour of investigation, maybe it's related to the new multisrc structure?~~ 

Doesn't seem to be related with the multisrc, maybe something change on kemono's side?

### edit: definitely from kemono's side, coomer is also broken with the same error

Here are some logs and screenshots

![Screenshot_2024-11-26-15-36-10-762_app mihon-edit~2](https://github.com/user-attachments/assets/80805171-4572-4c2e-8d07-757e5fc32813)
![Screenshot_2024-11-26-15-54-08-521_com cxinventor file explorer](https://github.com/user-attachments/assets/366b15b0-d2bd-47e5-ab91-e6d87dc76b0d)

logs:

[mihon_crash_logs.txt](https://github.com/user-attachments/files/17916827/mihon_crash_logs.txt)

~~Edit: rolling back the kemono extension from 1.4.14 to 1.4.12 or 1.4.13 does not fix the problem.~~ it's from upstream (kemono's side)

**Comment by Norsze** [comment]
@towermom9 

Please note that creating an issue does not mean that the source will be added or fixed in a timely fashion, because the work is volunteer-based. Some sources may also be impossible to do or prohibitively difficult to maintain.

If you would like to see a request fulfilled and have the necessary skills to do so, consider contributing! Issues are up-for-grabs for any developer if there is no assigned user already.

DO NOT PING DEVS!

They have personal lives and do this in their free time for free

**Comment by towermom9** [comment]
gary25566 over on discord made a great point:
"sometimes whenever going to webview, Kemono sidebar seems to be blocking the extension from viewing images. But when the webview does not show the sidebar, means the images can be viewed."

After I tested it, yes the sidebar does indeed automatically open whenever going to the webview

Note: changing the user agent string to a desktop one does not fix the problem

**Comment by towermom9** [comment]
https://kemono.su/documentation/api

This would probably be useful 🤔

**Comment by lalalasupa0** [comment]
The Fields thing error is still there, I'm using Yōkai Nightly

Artist page on Kemono: dojiro
Chapter: `お金を払うと童貞をもらってくれる義理の妹【#有料少女】【6P漫画・高画質版】 `

![IMG_20241202_153429](https://github.com/user-attachments/assets/e114a06c-ba0c-4270-b7b5-1387b33d2b20)

^ notification while downloading

**Comment by 0Ha16wA5** [comment]
@lalalasupa0 You should make new issues for better visibilities.
(I also have the same problem with some selected entry)

**Comment by lalalasupa0** [comment]
> @lalalasupa0 You should make new issues for better visibilities. (I also have the same problem with some selected entry)

> Commenting unnecessarily sends an email to everyone involved in the issue & pings the server channel.

Do you know if that's not the case if an issue is closed? Maybe it's not necessary
